### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by rrjohnson85** [aks1376/ngx-input-errors#1]
I found this library on NPM (https://www.npmjs.com/package/ngx-input-errors), but the repo only shows a license file.  Is this project dead?  Can you publish the source code?

**Comment by aks1376** [comment]
because document is not complete yet, i didn't publish

but as soon as possible i will publish the source code

**Comment by rrjohnson85** [comment]
Thanks @aks1376, I look forward to it!

**Comment by aks1376** [comment]
as I said, I publish the source code
I hope it would be helpful for you
and it need lot of work to be completed
